### ISSUE TITLE
KVR page

### ISSUE THREAD

**Issue by firolightfog** [attilammagyar/attilammagyar.github.io#1]
Ez te vagy? 

https://www.kvraudio.com/product/js80p-by-attila-m-magyar

Az oldalon a JS80P link rossz.

**Comment by attilammagyar** [comment]
Melyik linkre gondosz, illetve hova kellene mutatnia?

**Comment by firolightfog** [comment]
<img width="655" alt="image" src="https://github.com/attilammagyar/attilammagyar.github.io/assets/34127628/f69d5f49-f847-4389-85ab-f8f4e2f10d22">

**Comment by attilammagyar** [comment]
Nálam mindegyik jó helyre mutat:
* a "Free / at attilammagyar.github.io" es a "JS80P" link a https://attilammagyar.github.io/js80p/ -re visz,
* a Linuxos és a Windows-os letöltés link a https://attilammagyar.github.io/js80p/#download -ra mutat,
* a saját nevem pedig a GitHub-os page-emre.

**Comment by firolightfog** [comment]
Ööö... itthonról is megnéztem. Innen mindent látok.
Elnézést, úgy néz ki az én hálózatomban volt a hiba!

...és nem csak látom, hanem hallom is. Gratulálok hozzá!

**Comment by attilammagyar** [comment]
Köszi szépen!

(Egyébként lehet, hogy az a gond, hogy egyes céges hálózatokban a `*.github.io` domainek elővigyázatosságból kollektíven le lehetnek tiltva.)
